# Generated by Django 4.2.7 on 2023-12-02 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='works',
        ),
        migrations.AddField(
            model_name='artist',
            name='work',
            field=models.ForeignKey(
                default='1', on_delete=django.db.models.deletion.CASCADE, to='artist.work'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='firstname',
            field=models.CharField(default='FirstName', max_length=30),
        ),
        migrations.AddField(
            model_name='customuser',
            name='lastname',
            field=models.CharField(default='LastName', max_length=30),
        ),
    ]
