# Generated by Django 4.2.7 on 2023-12-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_remove_artist_works_artist_work_customuser_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='link',
            field=models.URLField(default='https://youtube.com'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='work_type',
            field=models.CharField(choices=[('YT', 'Youtube'), ('IG', 'Instagram'), ('OT', 'Other')], default='YT', max_length=2),
        ),
    ]
