# Generated by Django 4.2.7 on 2023-12-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0003_customuser_link_customuser_work_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='work',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='link',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='work_type',
        ),
        migrations.AddField(
            model_name='artist',
            name='works',
            field=models.ManyToManyField(to='artist.work'),
        ),
    ]
