# Generated by Django 4.2.7 on 2023-12-02 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0005_customuser_firstname_customuser_lastname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='name',
            new_name='username',
        ),
    ]
