# Generated by Django 4.2.7 on 2023-12-03 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0008_alter_customuser_artist_id_alter_work_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='artist_id',
        ),
    ]
