# Generated by Django 4.2.7 on 2023-12-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0010_remove_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
