# Generated by Django 4.2.7 on 2023-12-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0012_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='work_type',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
